# Dockerfile for api/apiapp.py
FROM tensorflow/tensorflow:latest

WORKDIR /app

# Copy requirements and install
COPY requirements.txt .
RUN pip install --no-cache-dir --ignore-installed blinker==1.8.2 && \
    pip install --no-cache-dir --break-system-packages -r requirements.txt


# Copy the entire api/ directory
COPY api/ api/

# Expose port 7777
EXPOSE 7777

# Run apiapp.py
CMD ["/usr/bin/python3", "api/apiapp.py"]